import type { Email } from './types'

const now = Date.now()
const h = (hours: number) => new Date(now - hours * 3600 * 1000).toISOString()

/**
 * Conjunto de e-mails de exemplo. Em um app real, estes viriam de uma
 * conta conectada (IMAP / Gmail API / Microsoft Graph). Aqui simulam uma
 * caixa de entrada variada para demonstrar a triagem por relevância.
 */
export const SEED_EMAILS: Email[] = [
  {
    id: 'e1',
    from: 'Banco Central',
    fromEmail: 'alertas@meubanco.com.br',
    vip: true,
    subject: 'URGENTE: Fatura do cartão vence hoje',
    preview: 'O pagamento da sua fatura vence hoje. Evite juros...',
    body: 'Prezado cliente, o pagamento da sua fatura no valor de R$ 2.480,00 vence hoje. Ação necessária para evitar juros e multa. Acesse o app para pagar o boleto.',
    date: h(1),
    read: false,
    starred: false,
    hasAttachment: true,
    directed: true,
    folder: 'inbox',
    category: 'financeiro',
  },
  {
    id: 'e2',
    from: 'Ana Costa · RH',
    fromEmail: 'ana.costa@empresa.com',
    vip: true,
    subject: 'Reunião de aprovação do contrato amanhã',
    preview: 'Confirmar presença na reunião para revisar o contrato...',
    body: 'Oi! Precisamos da sua aprovação no contrato do novo projeto. Reunião importante marcada para amanhã às 10h. Pode confirmar presença? Segue a proposta em anexo.',
    date: h(2),
    read: false,
    starred: true,
    hasAttachment: true,
    directed: true,
    folder: 'inbox',
    category: 'trabalho',
  },
  {
    id: 'e3',
    from: 'Recrutamento TechCorp',
    fromEmail: 'talentos@techcorp.io',
    vip: false,
    subject: 'Convite para entrevista — vaga de Engenheiro',
    preview: 'Gostaríamos de agendar uma entrevista com você...',
    body: 'Olá! Analisamos seu perfil e gostaríamos de agendar uma entrevista. Por favor, confirme sua disponibilidade esta semana. Prazo para resposta: sexta-feira.',
    date: h(5),
    read: false,
    starred: false,
    hasAttachment: false,
    directed: true,
    folder: 'inbox',
    category: 'trabalho',
  },
  {
    id: 'e4',
    from: 'Carlos Mendes',
    fromEmail: 'carlos.m@parceiro.com',
    vip: false,
    subject: 'Re: Proposta comercial — decisão pendente',
    preview: 'Aguardo seu retorno sobre a proposta enviada...',
    body: 'Bom dia, aguardo seu retorno sobre a proposta comercial. Precisamos de uma decisão até o fim da semana para seguir com o projeto.',
    date: h(9),
    read: true,
    starred: false,
    hasAttachment: false,
    directed: true,
    folder: 'inbox',
    category: 'trabalho',
  },
  {
    id: 'e5',
    from: 'Escola do Pedro',
    fromEmail: 'secretaria@escola.edu.br',
    vip: false,
    subject: 'Confirmação de matrícula 2026',
    preview: 'A matrícula do aluno foi confirmada com sucesso...',
    body: 'Informamos que a matrícula foi confirmada. Segue o comprovante em anexo. Qualquer dúvida estamos à disposição.',
    date: h(20),
    read: false,
    starred: false,
    hasAttachment: true,
    directed: true,
    folder: 'inbox',
    category: 'pessoal',
  },
  {
    id: 'e6',
    from: 'GitHub',
    fromEmail: 'notifications@github.com',
    vip: false,
    subject: '[repo] Pull request #142 aguardando revisão',
    preview: 'Uma nova revisão foi solicitada em seu pull request...',
    body: 'Uma revisão foi solicitada. O pull request #142 está aguardando sua aprovação para ser mesclado.',
    date: h(12),
    read: true,
    starred: false,
    hasAttachment: false,
    directed: false,
    folder: 'inbox',
    category: 'atualizacoes',
  },
  {
    id: 'e7',
    from: 'LinkedIn',
    fromEmail: 'notify@linkedin.com',
    vip: false,
    subject: 'Você tem 5 novas visualizações de perfil',
    preview: 'Veja quem andou visitando seu perfil esta semana...',
    body: 'Sua rede está crescendo! Você teve 5 novas visualizações de perfil e 2 novas conexões esta semana.',
    date: h(28),
    read: true,
    starred: false,
    hasAttachment: false,
    directed: false,
    folder: 'inbox',
    category: 'social',
  },
  {
    id: 'e8',
    from: 'Loja Mega Ofertas',
    fromEmail: 'promo@megaofertas.com',
    vip: false,
    subject: '🔥 Black Friday antecipada: 70% OFF só hoje!',
    preview: 'Não perca! Descontos imperdíveis em toda a loja...',
    body: 'Promoção imperdível! Aproveite até 70% de desconto em toda a loja. Cupom grátis no primeiro pedido. Oferta expira à meia-noite. Descadastrar aqui.',
    date: h(30),
    read: true,
    starred: false,
    hasAttachment: false,
    directed: false,
    folder: 'inbox',
    category: 'promocoes',
  },
  {
    id: 'e9',
    from: 'Streaming+',
    fromEmail: 'no-reply@streamingplus.com',
    vip: false,
    subject: 'Novidades da semana na sua tela',
    preview: 'Confira os lançamentos que chegaram no catálogo...',
    body: 'Chegaram novidades no catálogo! Confira os lançamentos da semana e continue de onde parou.',
    date: h(50),
    read: true,
    starred: false,
    hasAttachment: false,
    directed: false,
    folder: 'inbox',
    category: 'promocoes',
  },
  {
    id: 'e10',
    from: 'Dra. Marina Silva',
    fromEmail: 'contato@clinica.com.br',
    vip: false,
    subject: 'Lembrete: consulta na próxima terça',
    preview: 'Este é um lembrete da sua consulta agendada...',
    body: 'Olá! Lembrando da sua consulta agendada para a próxima terça-feira às 15h. Confirme sua presença respondendo este e-mail.',
    date: h(40),
    read: false,
    starred: false,
    hasAttachment: false,
    directed: true,
    folder: 'inbox',
    category: 'pessoal',
  },
  {
    id: 'e11',
    from: 'Contabilidade XYZ',
    fromEmail: 'fiscal@contabil.com',
    vip: false,
    subject: 'Imposto a pagar — vencimento próximo',
    preview: 'Segue guia do imposto com vencimento em 3 dias...',
    body: 'Segue em anexo a guia do imposto. Atenção ao prazo: o vencimento é em 3 dias. Pagamento em atraso gera multa.',
    date: h(6),
    read: false,
    starred: false,
    hasAttachment: true,
    directed: true,
    folder: 'inbox',
    category: 'financeiro',
  },
  {
    id: 'e12',
    from: 'Comunidade Dev',
    fromEmail: 'digest@comunidadedev.com',
    vip: false,
    subject: 'Resumo semanal: os posts mais lidos',
    preview: 'Veja o que a comunidade mais leu esta semana...',
    body: 'Confira o resumo semanal com os artigos mais populares da comunidade. Newsletter enviada semanalmente.',
    date: h(66),
    read: true,
    starred: false,
    hasAttachment: false,
    directed: false,
    folder: 'inbox',
    category: 'atualizacoes',
  },
]
